name: MLops Project CICD WORKFLOW

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
    GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

jobs:
    integration:
        name: Continuous Integration
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run tests
            run: |
              pytest tests/

    Build:
        name: Build and test Docker Image
        runs-on: ubuntu-latest
        needs: integration
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build Docker image
            run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }} .

          - name : Scan Docker image with Trivy
            run: |
                docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                aquasec/trivy:latest image ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }} || true
    Deploy:
        name: Deploy to Docker Hub
        runs-on: ubuntu-latest
        needs: Build
        steps:
          - name: Login to Docker Hub
            run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          - name: Push Docker image
            run: docker push ${{secrets.DOCKERHUB_USERNAME}}/myapp:${{ github.sha }}


        